#define LAYER_BINDING(LAYER_NAME, BINDINGS, DISPLAY) \
layer_##LAYER_NAME { \
    bindings = < \
    BINDINGS \
    >; \
    display-name = DISPLAY; \
};

#define QWERTY_LAYER LAYER_BINDING(qwerty, QWERTY_BINDINGS, "QWERTY") 
#define COLEMAK_DH_LAYER LAYER_BINDING(colemak_dh, COLEMAK_DH_BINDINGS, "COLEMAK") 
#define QWERTY_TAP_LAYER LAYER_BINDING(qwerty_tap, QWERTY_TAP_BINDINGS, "TAP") 
#define NUMBER_LAYER LAYER_BINDING(number, NUMBER_BINDINGS, "NUMBER") 
#define SYMBOL_LAYER LAYER_BINDING(symbol, SYMBOL_BINDINGS, "SYMBOL") 
#define FUNC_LAYER LAYER_BINDING(func, FUNC_BINDINGS, "FUNC") 
#define NAVI_LAYER LAYER_BINDING(navi, NAVI_BINDINGS, "NAVI") 
#define MOUSE_LAYER LAYER_BINDING(mouse, MOUSE_BINDINGS, "MOUSE") 
#define MEDIA_LAYER LAYER_BINDING(media, MEDIA_BINDINGS, "MEDIA") 
#define BUTTON_LAYER LAYER_BINDING(button, BUTTON_BINDINGS, "BUTTON") 

